### ISSUE TITLE
getAssetFinalLocation override my doGetLocation once the minification is enabled

### ISSUE THREAD

**Issue by wmh** [dandelion/dandelion#67]
I wish to output an asset like this through a cdn server:
```
//mycdn.com/js/main.js
```

But once the minification is enabled, the url is override back to local path like this:
```
/dandelion-assets/5d9429063edafd554aeefdd70f5eb1b9/31454d2e8f9151da086054154667b03b/js/main-0.1.0.js
```

Anything I can do with this issue?

**Comment by tduchateau** [comment]
If you wish to use remote asset, first ensure to configure the asset with a `remote` location key in the bundle definition (*.json).
Then, if you wish the asset to be left untouched, consider it as a "vendor asset". In this case, just move the bundle definition under the `dandelion/vendor` folder within the classpath.

**Comment by wmh** [comment]
I wish to minify my own develop js file and serve it through cdn server from my own server.
So, it's not a remote file neither a vendor file. Any suggestion for me?

**Comment by tduchateau** [comment]
OK I see.

This simple and common use case is unfortunately not covered entirely by Dandelion today.

The issue here is that if you wish to serve assets as-is from a remote location (either your CDN or a vendor one), the only way is to declare bundles as "vendor". In this case, assets are left untouched and served from the remote location. This implies to preprocess assets at build-time since Dandelion won't touch them at run-time.

If you declare them with a remote location without considering the bundle as "vendor", remote assets are fetched, processed and served from your webapp, which can look weird but locators (components that interprets all location keys suh as `remote`, ...) are actually used as a "fetching strategy" instead of a "serving strategy".

Dandelion is a pure runtime solution for now. This has pros and cons.
However, the next major step in Dandelion-Core is to refactor the current asset processing into a real asset pipeline. I'm also considering the use of extra build-time steps to handle this kind of use case, but it's not an easy task since components have to handle dynamic assets as well.

So for now, I see 2 solutions:

1) Use an extra build tool such as Grunt or Gulp to process your assets. Once transferred remotely, configure your bundles as "vendor" anyway (create `*.json` files under the `dandelion/vendor` folder), and define assets with a `remote` location key.

2) Until the new asset pipeline is available, let Dandelion fetch, process and serve your assets from your web application. In other words, don't use a CDN :-/

Just a final note, from the generated link, I see you have set a version in the `main` asset definition. For this kind of asset (custom code, developed by you), just remove the version. Dandelion will use the right versioning strategy (based on the contents).

**Comment by wmh** [comment]
Okay, no problem. I'll try to build minify js using Grunt and rewrite doGetLocation to serve minified js in production server. Thank you very much. :+1:
